name: Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t gcr.io/iamretailer-281612/iar/krstore:1.0.0 .
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: iamretailer-281612
          image_name: gcr.io/iamretailer-281612/iar/krstore:1.0.0
