name: Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GCP Build and Push
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: iamretailer-281612
          image_name: krstore
          image_tag: 1.0.0
          dockerfile: ./Dockerfile  
      - name: Deploy Docker image
        run: gcloud run deploy krstorebb --image=krstore:1.0.0 --platform=managed --port=80 --allow-unauthenticated --service-account=bbpipeline@iamretailer-281612.iam.gserviceaccount.com --add-cloudsql-instances=iamretailer-281612:us-central1:ayyapan --region=us-central1 --project=iamretailer-281612
