name: Docker
on:
  push:
    branches: [Production]
env:
  PROJECT_ID: iamretailer-281612
  IMAGE_NAME: krstore
  IMAGE_TAG: 1.0.4
  SERVICE_NAME: krstorebb
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Gcr
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: Purge Cache
        uses: fjogeleit/http-request-action@master
        with:
          url: "http://ddemo.accozen.co.in/cloudflare/purgecache.php"
          method: "GET"
      - name: Setup Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: bbpipeline@iamretailer-281612.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      - name: Build and Push Container
        run: |-
          #docker build -t gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} .
          #docker push gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          gcloud config set project ${{env.PROJECT_ID}}
          #gcloud builds submit  --tag gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          #gcloud beta run domain-mappings create --service ${{env.SERVICE_NAME}} --platform managed --region us-central1 --project ${{env.PROJECT_ID}}  --domain krstoredemo.iar.net.in
      #  id: deploy
      #- uses: google-github-actions/deploy-cloudrun@main
      #  with: 
      #      image: gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
      #      service: ${{env.SERVICE_NAME}}
      #      credentials: ${{ secrets.GCLOUD_SERVICE_KEY }}
      #- name: Archive Release
      #  uses: thedoctor0/zip-release@master
      #  with:
      #    filename: 'app.zip'
      #    path: .
      #    exclusions: '*.git* /*node_modules/* .editorconfig'
      #- name: List
      #  run: ls
      #  id: upload-file
      #- uses: google-github-actions/upload-cloud-storage@main
      #  with:
      #    path: app.zip
      #    destination: gs://iar_themes/app.zip
