name: Docker
on:
  push:
    branches: [Production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Gcr
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: iamretailer-281612
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/iamretailer-281612/krstore:1.0.2 .
          docker push gcr.io/iamretailer-281612/krstore:1.0.2
        id: deploy
      - uses: google-github-actions/deploy-cloudrun@main
        with: 
            image: gcr.io/iamretailer-281612/krstore:1.0.2
            service: krstorebb
            credentials: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'app.zip'
          path: .
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: List
        run: ls
        id: upload-file
      - uses: google-github-actions/upload-cloud-storage@main
        with:
          path: app.zip
          destination: gs://iar_themes/app.zip
