name: Docker
on:
  push:
    branches: [production]
  pull_request:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Gcr
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: iamretailer-281612
          image_name: krstore
          image_tag: 1.0.0
          dockerfile: ./Dockerfile
        id: deploy
      - uses: google-github-actions/deploy-cloudrun@main
        with: 
            image: gcr.io/iamretailer-281612/krstore:1.0.0
            service: krstorebb
            credentials: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'app.zip'
          path: .
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: List
        run: ls
        id: upload-file
      - uses: google-github-actions/upload-cloud-storage@main
        with:
          path: app.zip
          destination: gs://iar_themes/app.zip
