name: Docker
on:
  pull_request:
    branches: [ master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Gcr
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: iamretailer-281612
          image_name: krstore
          image_tag: 1.0.0
          dockerfile: ./Dockerfile
        id: deploy
      - uses: google-github-actions/deploy-cloudrun@main
        with: 
            image: gcr.io/iamretailer-281612/krstore:1.0.0
            service: krstorebb
            credentials: ${{ secrets.GCLOUD_SERVICE_KEY }}
